### ISSUE TITLE
Invalid exception raised

### ISSUE THREAD

**Issue by skyblockz** [TowardtheStars/Python-NBT#1]
Traceback (most recent call last):
  File "C:\Users\natha\AppData\Local\Programs\Python\Python38\lib\site-packages\discord\ext\commands\core.py", line 79, in wrapped
    ret = await coro(*args, **kwargs)
  File "C:/Users/natha/Documents/Python Projects/PriceBot/PriceBot.py", line 2184, in test
    await updateAuction()
  File "C:\Users\natha\Documents\Python Projects\PriceBot\utils\auctions.py", line 35, in updateAuction
    item_bytes = nbt.read_from_nbt_file('temp.nbt').json_obj
  File "C:\Users\natha\AppData\Local\Programs\Python\Python38\lib\site-packages\python_nbt\nbt.py", line 429, in read_from_nbt_file
    return TAGLIST[_type](buffer=_file)
  File "C:\Users\natha\AppData\Local\Programs\Python\Python38\lib\site-packages\python_nbt\nbt.py", line 242, in __init__
    self._read_buffer(buffer)
  File "C:\Users\natha\AppData\Local\Programs\Python\Python38\lib\site-packages\python_nbt\nbt.py", line 253, in _read_buffer
    tag = TAGLIST[_type](buffer=buffer)
  File "C:\Users\natha\AppData\Local\Programs\Python\Python38\lib\site-packages\python_nbt\nbt.py", line 351, in __init__
    super().__init__(
  File "C:\Users\natha\AppData\Local\Programs\Python\Python38\lib\site-packages\python_nbt\nbt.py", line 127, in __init__
    self._read_buffer(buffer)
  File "C:\Users\natha\AppData\Local\Programs\Python\Python38\lib\site-packages\python_nbt\nbt.py", line 369, in _read_buffer
    self.append(TAGLIST[self._tag_type_id](buffer=buffer))
  File "C:\Users\natha\AppData\Local\Programs\Python\Python38\lib\site-packages\python_nbt\nbt.py", line 242, in __init__
    self._read_buffer(buffer)
  File "C:\Users\natha\AppData\Local\Programs\Python\Python38\lib\site-packages\python_nbt\nbt.py", line 253, in _read_buffer
    tag = TAGLIST[_type](buffer=buffer)
  File "C:\Users\natha\AppData\Local\Programs\Python\Python38\lib\site-packages\python_nbt\nbt.py", line 242, in __init__
    self._read_buffer(buffer)
  File "C:\Users\natha\AppData\Local\Programs\Python\Python38\lib\site-packages\python_nbt\nbt.py", line 253, in _read_buffer
    tag = TAGLIST[_type](buffer=buffer)
  File "C:\Users\natha\AppData\Local\Programs\Python\Python38\lib\site-packages\python_nbt\nbt.py", line 242, in __init__
    self._read_buffer(buffer)
  File "C:\Users\natha\AppData\Local\Programs\Python\Python38\lib\site-packages\python_nbt\nbt.py", line 253, in _read_buffer
    tag = TAGLIST[_type](buffer=buffer)
  File "C:\Users\natha\AppData\Local\Programs\Python\Python38\lib\site-packages\python_nbt\nbt.py", line 275, in __init__
    super().__init__(
  File "C:\Users\natha\AppData\Local\Programs\Python\Python38\lib\site-packages\python_nbt\nbt.py", line 127, in __init__
    self._read_buffer(buffer)
  File "C:\Users\natha\AppData\Local\Programs\Python\Python38\lib\site-packages\python_nbt\nbt.py", line 283, in _read_buffer
    self.extend(list(bytearray(buffer.read(length))))
  File "C:\Users\natha\AppData\Local\Programs\Python\Python38\lib\site-packages\python_nbt\_util.py", line 96, in extend
    raise "Contains value that cannot be put into this RestricList"
TypeError: exceptions must derive from BaseException

**Comment by TowardtheStars** [comment]
Thank you for your contribution. This is fixed in v1.1.0.
